import { HandleError } from '@/lib/utils/error-handling/types'
import { AuthError } from 'next-auth'

/**
 * @function handleAuthError
 * @description Handles authentication-related errors generated by the NextAuth.js (Auth.js) library.
 * The function analyzes the type of `AuthError` and returns a standardized `HandleError` object,
 * which can be used for informing the user or for logging purposes.
 *
 * @param  error - The authentication error object received from NextAuth.js.
 * @returns  - A standardized error object including `type`, `message`, and `details`.
 */
export function handleAuthError(error: AuthError): HandleError {
  // Uses a `switch` statement to handle different types of `AuthError`.
  // Each `case` corresponds to a specific error type defined by NextAuth.js.
  switch (error.type) {
    // Handles the error that occurs when provided credentials (e.g., username/password) are invalid.
    case 'CredentialsSignin':
      return {
        type: 'authenticate', // Error category: authentication
        message: 'Invalid credentials.', // Message for the user
        details: undefined, // No additional details provided in this case
      }
    // Handles all other unrecognized or general `AuthError` types.
    default:
      return {
        type: 'authenticate', // Error category: authentication
        message: 'Something went wrong.', // Generic error message
        details: undefined, // No additional details provided
      }
  }
}
